In [3]:
#list can hold values of different datatypess
#drawbacks of lists
#introduction to numpy arrays
#converting lists to array?
#indexing and calling elemnt out of list range
#np.mean,median,sum,
#arr.ndim
#reading csv file and calling simple pandas functions head, tail, info, describe


In [5]:

l1=[1,2,3,4]
l2=[8,9,0,5]

print(l1+l2)
#not expected output in case of lists, just concatenation happens


[1, 2, 3, 4, 8, 9, 0, 5]


In [ ]:
marks=[45,67,90]
name=["ali", "ahmed", "muhammad"]
plt.plot(name, marks)

In [1]:
##nested if revision
a=5
b=7
c=8
if(a>b):
    print("a is greater than b")
    if (9>3):
        print("nested if condition is true")

# no output because outer if condition is false

In [3]:
a=[9,7,8,1,24,3]

In [5]:
type(a)

list

In [7]:
sum(a) 

52

In [9]:
a.append(8)

In [11]:
a

[9, 7, 8, 1, 24, 3, 8]

## list.extend()

In [14]:
a

[9, 7, 8, 1, 24, 3, 8]

In [16]:
a.extend([1,2,3])

In [18]:
a

[9, 7, 8, 1, 24, 3, 8, 1, 2, 3]

In [20]:
original= [1,2,3]
list2=[4,5,6,7]

In [22]:
original.extend(list2)

In [24]:
a=[23,6,87,123]

In [26]:
len(a)

4

In [28]:
#a[index]
a[3]

123

In [30]:
a[0]

23

In [32]:
a[4]

IndexError: list index out of range

In [34]:
a

[23, 6, 87, 123]

In [36]:
for i in a:
    print(i)

23
6
87
123


## lists can store different datatypes

In [38]:
new_list=["ahmed", 23, 1.56, "ali"]

In [40]:
for i in new_list:
    print(i)
    print(type(i))

ahmed
<class 'str'>
23
<class 'int'>
1.56
<class 'float'>
ali
<class 'str'>


In [42]:
sum(new_list)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

## introduction to numpy arrays

In [45]:
!pip install numpy

In [47]:
import numpy

In [49]:
arr1=numpy.array([1,2,4])

In [51]:
arr1

array([1, 2, 4])

In [53]:
arr1=numpy.array([1,2,4, "ali", "ahmed"])
for i in arr1:
    print(i)
    print(type(i))

1
<class 'numpy.str_'>
2
<class 'numpy.str_'>
4
<class 'numpy.str_'>
ali
<class 'numpy.str_'>
ahmed
<class 'numpy.str_'>


## lists can store different data types but numpy arrays convert them into same without error

In [56]:
list1=[1,2,3]
list2=[4,5,6]
print(list1+list2)

[1, 2, 3, 4, 5, 6]


In [58]:
# element wise addition not possible

In [60]:
list1*2

[1, 2, 3, 1, 2, 3]

## conveting lists into numpy array

In [65]:
import numpy as np

In [67]:
arr1=np.array(list1)
arr2=np.array(list2)

In [69]:
type(arr1)

numpy.ndarray

In [71]:
arr1+arr2

array([5, 7, 9])

In [73]:
arr2*2

array([ 8, 10, 12])

In [75]:
arr1

array([1, 2, 3])

In [77]:
sum(arr1)

6

In [79]:
np.mean(arr1)

2.0

In [81]:
np.median(arr1)

2.0

In [83]:
np.mode(arr1)

AttributeError: module 'numpy' has no attribute 'mode'

In [85]:
arr1.ndim

1

In [87]:
arr1.shape

(3,)

In [91]:
list2d=[[1,2,3], [3,4,5]]

In [93]:
array2d=np.array(list2d)

In [95]:
array2d

array([[1, 2, 3],
       [3, 4, 5]])

In [101]:
array2d.ndim

2

In [103]:
array2d.shape

(2, 3)

## reading excel dataset in python

In [108]:
!pip install pandas

In [110]:
import pandas as pd

In [116]:
data=pd.read_csv("D:/student_dataset.csv")

In [120]:
data.head()

StudentID      Name  Age  Gender      Grade  Attendance  FinalExamScore
0     S0001  Student1   25    Male  60.212228          85       78.652064
1     S0002  Student2   20    Male  96.532454         100       72.347071
2     S0003  Student3   24  Female  79.203509          35       88.799927
3     S0004  Student4   24    Male  65.519182          54       66.332211
4     S0005  Student5   17    Male  62.680631          53       43.787086

In [122]:
data.head(3)

StudentID      Name  Age  Gender      Grade  Attendance  FinalExamScore
0     S0001  Student1   25    Male  60.212228          85       78.652064
1     S0002  Student2   20    Male  96.532454         100       72.347071
2     S0003  Student3   24  Female  79.203509          35       88.799927

In [124]:
data.head(8)

StudentID      Name  Age  Gender      Grade  Attendance  FinalExamScore
0     S0001  Student1   25    Male  60.212228          85       78.652064
1     S0002  Student2   20    Male  96.532454         100       72.347071
2     S0003  Student3   24  Female  79.203509          35       88.799927
3     S0004  Student4   24    Male  65.519182          54       66.332211
4     S0005  Student5   17    Male  62.680631          53       43.787086
5     S0006  Student6   17    Male  71.868357          84       75.846523
6     S0007  Student7   18  Female  86.301672           9       72.293310
7     S0008  Student8   17    Male  73.345534          11       90.620405

In [126]:
data.tail()

StudentID        Name  Age  Gender      Grade  Attendance  FinalExamScore
495     S0496  Student496   16  Female  73.928348          10       63.297157
496     S0497  Student497   23    Male  63.353273          36       66.540411
497     S0498  Student498   17  Female  78.387603          11       83.505418
498     S0499  Student499   23    Male  95.011317          85       54.545547
499     S0500  Student500   19    Male  90.531636          56       60.780361

In [128]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   StudentID       500 non-null    object 
 1   Name            500 non-null    object 
 2   Age             500 non-null    int64  
 3   Gender          500 non-null    object 
 4   Grade           500 non-null    float64
 5   Attendance      500 non-null    int64  
 6   FinalExamScore  500 non-null    float64
dtypes: float64(2), int64(2), object(3)
memory usage: 27.5+ KB


In [130]:
data.describe()

Age       Grade  Attendance  FinalExamScore
count  500.00000  500.000000   500.00000      500.000000
mean    20.51400   79.916892    50.64400       69.643785
std      2.91527   11.226716    29.81441       17.716107
min     16.00000   60.109527     0.00000       40.035899
25%     18.00000   70.317206    24.00000       53.337397
50%     21.00000   80.378709    52.00000       70.101841
75%     23.00000   89.286620    77.00000       84.955109
max     25.00000   99.955384   100.00000       99.995500

In [132]:
pd.read_csv("D:/check.csv")

name  age  marks
0  shahzaib   21     50
1       ali   26     89

In [134]:
list1=[1,56,34,45]
list1.sort()

In [136]:
list1

[1, 34, 45, 56]

In [138]:
list2=[45,67,1,2]
list2=list2.sort()

In [142]:
print(list2)

None
